language: node_js
install: npm install
script: true
before_deploy:
- rm .eslintrc.js
- rm .gitignore
- cd .github
- rm *
- cd ..
- rmdir .github
- cd heroku_server
- rm *
- cd ..
- rmdir heroku_server
- rm index.js
- rm .travis.yml
- rm test.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  fqdn: elementnet.js.org
